In [1]:
import pandas as pd
df = pd.read_csv("../data/Library_Usage.csv")

In [2]:
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,1,Juvenile,0,0,0 to 9 years,r3,Richmond,NaN,NaN,z,Email,True,2022,True
1,2,Teen,0,0,10 to 19 years,x,Main,NaN,NaN,z,Email,True,2022,True
2,0,Adult,0,0,35 to 44 years,m4,Merced,NaN,NaN,z,Email,True,2019,True
3,2,Teen,0,0,10 to 19 years,x,Main,NaN,NaN,z,Email,True,2021,True
4,2,Teen,0,0,10 to 19 years,b2,Bayview,NaN,NaN,z,Email,True,2013,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437110,0,Adult,14,11,45 to 54 years,x,Main,August,2004.0,z,Email,True,2003,False
437111,0,Adult,2,0,45 to 54 years,x,Main,August,2004.0,z,Email,True,2003,True
437112,3,Senior,5,0,75 years and over,e7,Eureka Valley,August,2004.0,p,Phone,False,2003,True
437113,3,Senior,4,0,65 to 74 years,m6,Mission,August,2004.0,z,Email,True,2004,True
437114,3,Senior,3,9,65 to 74 years,p9,Presidio,August,2004.0,z,Email,True,2004,True

In [3]:
df.dropna()

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
40592,0,Adult,0,0,25 to 34 years,m8,Mission Bay,January,2023.0,z,Email,True,2017,True
40593,0,Adult,6,0,35 to 44 years,x,Main,January,2023.0,z,Email,True,2017,False
40594,1,Juvenile,2236,2295,10 to 19 years,o7,Ortega,January,2023.0,z,Email,True,2011,True
40595,0,Adult,49,13,60 to 64 years,r3,Richmond,January,2023.0,z,Email,True,2011,True
40596,2,Teen,1407,1091,10 to 19 years,o2,Ocean View,January,2023.0,z,Email,True,2012,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437110,0,Adult,14,11,45 to 54 years,x,Main,August,2004.0,z,Email,True,2003,False
437111,0,Adult,2,0,45 to 54 years,x,Main,August,2004.0,z,Email,True,2003,True
437112,3,Senior,5,0,75 years and over,e7,Eureka Valley,August,2004.0,p,Phone,False,2003,True
437113,3,Senior,4,0,65 to 74 years,m6,Mission,August,2004.0,z,Email,True,2004,True
437114,3,Senior,3,9,65 to 74 years,p9,Presidio,August,2004.0,z,Email,True,2004,True

In [4]:
len(df)

437115

In [5]:
len(df) - df.count()

Patron Type Code                    0
Patron Type Definition              0
Total Checkouts                     0
Total Renewals                      0
Age Range                         927
Home Library Code                   2
Home Library Definition             0
Circulation Active Month        40592
Circulation Active Year         40592
Notice Preference Code              0
Notice Preference Definition        0
Provided Email Address              0
Year Patron Registered              0
Within San Francisco County         0
dtype: int64

In [6]:
df.isna().sum()

Patron Type Code                    0
Patron Type Definition              0
Total Checkouts                     0
Total Renewals                      0
Age Range                         927
Home Library Code                   2
Home Library Definition             0
Circulation Active Month        40592
Circulation Active Year         40592
Notice Preference Code              0
Notice Preference Definition        0
Provided Email Address              0
Year Patron Registered              0
Within San Francisco County         0
dtype: int64

In [7]:
df_clean = df.dropna()
df_clean.isna().sum()

Patron Type Code                0
Patron Type Definition          0
Total Checkouts                 0
Total Renewals                  0
Age Range                       0
Home Library Code               0
Home Library Definition         0
Circulation Active Month        0
Circulation Active Year         0
Notice Preference Code          0
Notice Preference Definition    0
Provided Email Address          0
Year Patron Registered          0
Within San Francisco County     0
dtype: int64

In [8]:
len(df) - len(df_clean)

41343

In [9]:
df_clean.to_csv('Library_Usage_Clean.csv.ipynb', index=False)